AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda
Parameters:
  SqsScheduler:
    Type: String
    Description: SQS queue for submitting scheduler jobs
    Default: arn:aws:sqs:us-west-2:978103014270:MoistureSensorScheduler
  SqsUpdateActuator:
    Type: String
    Description: SQS queue for sending actuator update requests to grpc-server
    Default: arn:aws:sqs:us-west-2:978103014270:MoistureSensorUpdateActuator
  SnsTopic:
    Type: String
    Description: SNS topic for sending notifications
    Default: arn:aws:sns:us-west-2:978103014270:MoistureSensorPushNotificationTopic
Resources:
  # IAM
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-LambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:PublishMessage
                  - sqs:SendMessage
                  - sqs:SendMessageBatch
                  - sqs:GetQueueUrl
                Resource:
                  - !Ref SqsScheduler
                  - !Ref SqsUpdateActuator
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref SnsTopic
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  # Lambda functions
  LambdaIotEventHandler:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - arm64
      FunctionName: !Sub ${AWS::StackName}-IotEventHandler
      Description: Iot Events handler which submits scheduler jobs and notifies user of IoT events
      Handler: bootstrap
      Runtime: provided.al2
      Role: !GetAtt LambdaExecutionRole.Arn
      MemorySize: 256
      Timeout: 10
      ReservedConcurrentExecutions: 5
      CodeUri: ./IotEventHandler/
